### PR TITLE
Add short constructors for points, to match the ones for vectors

### PR DESCRIPTION
**Pull request by nstoddard**
In my code I find that I need to create points almost as often as vectors, so having short constructors is helpful.

### CODE REVIEW

**Comment by kvark** [comment]
Looks good! I'd like an extra review on cgmath before we merge.

**Comment by kvark** [comment]
Err, simd stuff. How does it compile for other PRs?..
bors retry

**Comment by nstoddard** [comment]
Can this be merged? I'm pretty sure the failed check isn't due to this PR.

**Comment by kvark** [comment]
bors retry

**Comment by kvark** [comment]
Trying to address the SIMD issue in #478

**Comment by kvark** [comment]
scheduling to land after #478 
bors retry

**Pull request merged**
