### PR TITLE
Add support for cast using bytemuck crate

### PR DESCRIPTION
**Pull request by maku693**
Added support for [bytemuck](https://docs.rs/bytemuck) crate.

I also applied `cargo fmt`, but I think it is out of scope, so I can remove that changes if you mind.

### CODE REVIEW

**Comment by Rua** [comment]
Good idea! I just came looking for this, and you read my mind.

**Comment by kvark** [comment]
Thank you for the PR!
Does that match what any other libraries are doing?

**Comment by maku693** [comment]
I think yes.

`bytemuck` [offers derive macro for that purpose](https://docs.rs/bytemuck/latest/bytemuck/derive.Pod.html), but it cannot be used for generic structs.

[glam](https://github.com/bitshifter/glam-rs/blob/e5a183a53a8037f4ce6c608ee3dd8c130d862507/src/features/impl_bytemuck.rs) does this too (but not using macros).

**Comment by Rua** [comment]
Nalgebra does as well.

**Review by kvark — APPROVED** [review]

**Pull request merged**
