### PR TITLE
Release 0.18

### LINKED ISSUE #499: Release 0.18?
Would it be possible to see a new release sometime soon? I'm trying to trim down dependencies and the rand crate was made optional about a year ago. It would be nice to exclude that when it's not needed.

### PR DESCRIPTION
**Pull request by kvark**
Closes #499
r? @aloucks  (check the invites on github and crates)

### CODE REVIEW

**Comment by fintelia** [comment]
Is there anything blocking this?

**Comment by kvark** [comment]
@aloucks was there anything that we still need to do?

**Comment by aloucks** [comment]
@kvark No, I think this is good.

**Comment by kvark** [comment]
bors r=aloucks

**Pull request merged**
