### PR TITLE
Mat3 constructors enhancement

### PR DESCRIPTION
**Pull request by AndreaCatania**
The reason of this PR is because I need to transform thing in a 2d plane, and these functions are really handy.

- Added to the Mat3 the possibility to be constructed from a translation vector, similarly to the Mat4.
- Added unit tests.

### CODE REVIEW

**Comment by kvark** [comment]
Could you please separate functional changes from `rustfmt` pass?

**Comment by AndreaCatania** [comment]
Yes, I saw that rust fmt formats a lot of files (even files not changed by
this pr); do you want that I add all these?

**Comment by kvark** [comment]
Sure! Just make it a separate commit please.

**Comment by AndreaCatania** [comment]
Done

**Pull request merged**
